<?php
require_once(ORD_LI_DIR . 'App/Order/View-orders.php');
echo $product_image;
echo "<br>";
echo 'قیمت محصول :' . $product_price;
echo "عنوان محصول : " . $product_title;
echo "<br>";
echo " پیوند یکتا محصول :  <a href='$product_url'>مشاهده محصول</a>";
echo "<br>";
echo "تخفیف :" . $discountTotal;
echo '<br>';
echo "شماره سفارش :" . $order_id;
echo '<br>';
echo " هزینه حمل و نقل :" . $shippingTotal;
echo '<br>';
echo " مبلغ سفارش :" . $total;
echo '<br>';
echo "  تحویل گیرنده : " . $firstName . ' ' . $lastName;
echo '<br>';
echo "آدرس : " . $address;
echo "<br>";
echo "کد پستی : " . $postcode;
echo "<br>";
echo " شماره تماس : " . $phone;
echo "<br>";
echo "  روش پرداخت : " . $payment;
echo "<br>";
echo "تاریخ ثبت سفارش : " . $order_date;
echo "<br>";
echo "تاریخ  پرداخت : " . $payment_date;
echo "<br>";
echo "  مبلغ پرداخت شده : " . $paymentTotal;
echo "<br>";
echo "تعداد ایتم های سفارش" . $product_count;
?>